### ISSUE TITLE
company-anaconda doesn't return candidates while anaconda-mode-complete does

### ISSUE THREAD

**Issue by valignatev** [pythonic-emacs/company-anaconda#27] opened 2018-04-09 05:46 UTC
I want to check all possible candidates in company tooltip even without any prefixes, for example (`|` is cursor):

```python
from os import |
```
Then I call `anaconda-mode-complete` and I have a bunch of candidates from os module in `*Completions*` buffer:
![image](https://user-images.githubusercontent.com/7038954/38481115-862ef6ae-3c0c-11e8-92ae-6704279e9ab8.png)

But if I call `company-manual-begin` or `company-complete` or `company-begin-backend` with `company-anaconda` it says `Cannot complete at point`.

I tried to slam through `company-anaconda` source code, but my elisp knowledge doesn't allow me to properly understand it. I think it somehow related to prefix detecting, but I'm not sure.

Anyway, thanks for an awesome package!

**Comment by proofit404** [comment] 2018-04-21 10:37
It's indeed problem with the prefix function.

**Comment by valignatev** [comment] 2018-04-21 11:27
Can I hope for a quick fix? :wink:

**Comment by proofit404** [comment] 2018-04-21 12:28
Sure! Let me know if you need assistance.

**Comment by proofit404** [comment] 2018-04-30 00:15
Should be fixed in the master. Feel free to reopen.

**Comment by Purring** [comment] 2018-04-30 00:32
I just updated my emacs a few minutes ago (unrelated to this ticket), and it failed with `Error (bytecomp): Symbol’s value as variable is void: rx-constituents`, and whenever i should get autocompletion in a file, i get `Company: backend company-anaconda error "Symbol’s value as variable is void: rx-constituents" with args (prefix)`.

**Comment by proofit404** [comment] 2018-04-30 00:39
Emacs version?

**Comment by Purring** [comment] 2018-04-30 00:43
25.3.1

**Comment by Purring** [comment] 2018-04-30 00:53
Nevermind, the issue resolved itself after I removed **all** my packages and reinstalled them. Maybe it's a quelpa issue with its cache? Its  certainly not company-anacondas.

**Comment by valignatev** [comment] 2018-04-30 01:12
Just tried master branch, still doesn't work for me. I'm using Emacs 26 RC. `anaconda-mode-complete` still works, `company-manual-begin` and `company-begin-backend` with `company-anaconda` doesn't. In `*Messages*` buffer I see:
```user-error: Cannot complete at point```

**Comment by valignatev** [comment] 2018-04-30 10:31
What about candidates after `from`? Or just without any context?
I have this when I press space after `from`:
```python
Traceback (most recent call last):
  File "/home/vj/.emacs.d/anaconda-mode/0.1.9/service_factory-0.1.5-py3.6.egg/service_factory/service.py", line 101, in apply
    result = method(**params)
  File "/home/vj/.emacs.d/anaconda-mode/0.1.9/anaconda_mode-0.1.9-py3.6.egg/anaconda_mode.py", line 30, in wrapper
    return f(Script(source, line, column, path))
  File "/home/vj/.emacs.d/anaconda-mode/0.1.9/anaconda_mode-0.1.9-py3.6.egg/anaconda_mode.py", line 50, in wrapper
    for definition in f(script)]
  File "/home/vj/.emacs.d/anaconda-mode/0.1.9/anaconda_mode-0.1.9-py3.6.egg/anaconda_mode.py", line 50, in <listcomp>
    for definition in f(script)]
  File "/usr/lib/python3.6/site-packages/jedi/api/classes.py", line 286, in full_name
    path = list(self._path())
  File "/usr/lib/python3.6/site-packages/jedi/api/classes.py", line 188, in _path
    return reversed(list(to_reverse()))
  File "/usr/lib/python3.6/site-packages/jedi/api/classes.py", line 164, in to_reverse
    for n in reversed(module_context.py__name__().split('.')):
AttributeError: 'ImplicitNamespaceContext' object has no attribute 'py__name__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vj/.emacs.d/anaconda-mode/0.1.9/service_factory-0.1.5-py3.6.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/vj/.emacs.d/anaconda-mode/0.1.9/service_factory-0.1.5-py3.6.egg/service_factory/service.py", line 50, in __call__
    result = self.apply(method, args)
  File "/home/vj/.emacs.d/anaconda-mode/0.1.9/service_factory-0.1.5-py3.6.egg/service_factory/service.py", line 105, in apply
    server_error(args['id'], error)
  File "/home/vj/.emacs.d/anaconda-mode/0.1.9/service_factory-0.1.5-py3.6.egg/service_factory/errors.py", line 91, in server_error
    raise ServiceException(500, dumps(response))
service_factory.exceptions.ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"code": -32000, "message": "Server error", "data": "AttributeError(\\"\'ImplicitNamespaceContext\' object has no attribute \'py__name__\'\\",)"}}')
```

**Comment by proofit404** [comment] 2018-04-30 10:38
1. This is error we should report to jedi probably.

2. `without any context` what do you mean?

**Comment by valignatev** [comment] 2018-04-30 10:39
Checking further, it works after `from` with jedi==0.11.1 (previously I tried 0.12), but still can't complete with no context (e.g. at the beginning of a line), although `anaconda-mode-complete` can.

**Comment by proofit404** [comment] 2018-04-30 10:54
Yes, can confirm prefix function does not work with empty lines.

**Comment by saskenuba** [comment] 2018-05-04 06:33
I'm using spacemacs on develop branch and jedi 0.12.0, and I got the same issue when trying to complete without context or access object methods. These errors pops up:
```
Company: An error occurred in auto-begin
Company: backend company-capf error "Nothing to complete" with args (prefix)
```
Using `anaconda-mode-complete` with context works fine.

When importing libraries/variables to `Inferior Python` buffer, everything works normally on both buffers, so `company-capf` uses a cache system right? Because a new variable at the repl, will appear for completion at the original `Python` buffer. Is this behavior intended?

**Comment by Compro-Prasad** [comment] 2018-07-05 06:17
I don't know what are you all talking about but it seems I can relate to this because `comany-anaconda` cannot complete with proper completions after `from os import |` but `anaconda-mode-complete` returns proper completions.

**Comment by introom** [comment] 2019-04-12 12:36
i am having the same issue that,

company-anaconda cannot complete `from os import |`
but anaconda-mode-complete can complete as usual.

**Comment by rzpilgrim** [comment] 2019-04-16 13:45
@introom I am also having this issue. I tried reinstalling everything from ELPA/MELPA, and it does not work. `anaconda-mode-complete` works as expected, though.

**Comment by CeleritasCelery** [comment] 2019-09-13 14:10
What is your output of `company-diag`? At the point where it should complete?

**Comment by theFool32** [comment] 2019-12-22 12:46
For a simple python file with:
```python
a = []
a.|
```
`company-anaconda` gives 
```
Server error: TypeError("py__call__() missing 1 required positional argument: 'arguments'")
```
`anaconda-mode-complete` works as expected.

**Comment by CeleritasCelery** [comment] 2019-12-22 16:52
Does `anaconda-mode-complete` return the same thing?

**Comment by theFool32** [comment] 2019-12-23 06:17
`anaconda-mode-complete` can return correct results.

**Comment by ioreshnikov** [comment] 2020-01-28 15:01
@CeleritasCelery I played with the debugger a bit, and I think I understand what's the issue is. Take a look at the prefix function:
```lisp
(defun company-anaconda-prefix ()
  "Grab prefix at point."
  (and anaconda-mode
       (not (company-in-string-or-comment))
       (company-anaconda-at-the-end-of-identifier)
       (let* ((line-start (line-beginning-position))
              (start
               (save-excursion
...
```
One of the first checks we do is whether we are at the end of the identifier, and in case of `from os import |` we are definitely not. If I comment out the line with `(company-anaconda-at-the-end-of-identifier)` it seems to be working, though the completions now include the whole line
![Screenshot from 2020-01-28 15-53-00](https://user-images.githubusercontent.com/1098912/73274738-5904ed00-41e6-11ea-9e1f-7f63deabe34d.png)

**Closed** 2020-01-29 18:31 UTC
Labels: bug

**Comment by CeleritasCelery** [comment] 2020-01-29 18:32
Thanks @ioreshnikov for looking into this! I submitted a fix. Please test.

**Comment by ioreshnikov** [comment] 2020-02-14 12:19
@CeleritasCelery sorry, missed your message. Yes, it seems to have fixed it, thanks!
